targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/presentation/pages/*.dart
            - lib/presentation/pages/**/*.dart
            - lib/usecase/*.dart
            - lib/usecase/**/*.dart
      mockito|mockBuilder:
        generate_for:
          - test/**.dart